title: Lucifer's Blog
description: "Nothing is trustworthy"
author:
  name: "lucifer"
  email: "hoangdanh732005@gmail.com"
  url: "http://deRealLucifer.github.io"

google_analytics: UA-147356794-1

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "lucifer"
